#ifndef JUDD_GL_LOADER_H
#define JUDD_GL_LOADER_H
#include <GL/gl.h>
#include <GL/glext.h>
#ifdef _WIN32
#include <GL/wgl.h>
#include <GL/wglext.h>
#endif
#define JUDD_GLFN(name, upper) PFN##upper##PROC name;
JUDD_GLFN(glGenBuffers, GLGENBUFFERS)JUDD_GLFN(glBindBuffer, GLBINDBUFFER)JUDD_GLFN(glBindVertexArray, GLBINDVERTEXARRAY)JUDD_GLFN(glGenVertexArrays, GLGENVERTEXARRAYS)JUDD_GLFN(glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)JUDD_GLFN(glVertexAttribPointer, GLVERTEXATTRIBPOINTER)JUDD_GLFN(glBufferData, GLBUFFERDATA)JUDD_GLFN(glCreateProgram, GLCREATEPROGRAM)JUDD_GLFN(glGetShaderiv, GLGETSHADERIV)JUDD_GLFN(glCompileShader, GLCOMPILESHADER)JUDD_GLFN(glShaderSource, GLSHADERSOURCE)JUDD_GLFN(glCreateShader, GLCREATESHADER)JUDD_GLFN(glGetProgramInfoLog, GLGETPROGRAMINFOLOG)JUDD_GLFN(glDeleteShader, GLDELETESHADER)JUDD_GLFN(glGetShaderInfoLog, GLGETSHADERINFOLOG)JUDD_GLFN(glAttachShader, GLATTACHSHADER)JUDD_GLFN(glDeleteShader, GLDELETESHADER)JUDD_GLFN(glGetProgramiv, GLGETPROGRAMIV)JUDD_GLFN(glLinkProgram, GLLINKPROGRAM)JUDD_GLFN(glBindFragDataLocation, GLBINDFRAGDATALOCATION)JUDD_GLFN(glUseProgram, GLUSEPROGRAM)JUDD_GLFN(glGetAttribLocation, GLGETATTRIBLOCATION)JUDD_GLFN(glGenVertexArrays, GLGENVERTEXARRAYS)JUDD_GLFN(glAttachShader, GLATTACHSHADER)JUDD_GLFN(glDetachShader, GLDETACHSHADER)JUDD_GLFN(glUseProgram, GLUSEPROGRAM)JUDD_GLFN(glGenerateMipmap, GLGENERATEMIPMAP)JUDD_GLFN(glGetUniformLocation, GLGETUNIFORMLOCATION)JUDD_GLFN(glUniform1i, GLUNIFORM1I)JUDD_GLFN(glUniform1f, GLUNIFORM1F)
void judd_load_gl();
#endif
#ifdef JUDD_GL_LOADER_IMPL
#undef JUDD_GL_LOADER_IMPL
#undef JUDD_GLFN
#ifdef _WIN32
#define JUDD_GLFN(name, upper) name = (PFN##upper##PROC)wglGetProcAddress(#name);
#endif
#ifdef __linux__
#define JUDD_GLFN(name, upper) name = (PFN##upper##PROC)glxGetProcAddress(#name);
#endif
void judd_load_gl(){
JUDD_GLFN(glGenBuffers, GLGENBUFFERS)JUDD_GLFN(glBindBuffer, GLBINDBUFFER)JUDD_GLFN(glBindVertexArray, GLBINDVERTEXARRAY)JUDD_GLFN(glGenVertexArrays, GLGENVERTEXARRAYS)JUDD_GLFN(glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)JUDD_GLFN(glVertexAttribPointer, GLVERTEXATTRIBPOINTER)JUDD_GLFN(glBufferData, GLBUFFERDATA)JUDD_GLFN(glCreateProgram, GLCREATEPROGRAM)JUDD_GLFN(glGetShaderiv, GLGETSHADERIV)JUDD_GLFN(glCompileShader, GLCOMPILESHADER)JUDD_GLFN(glShaderSource, GLSHADERSOURCE)JUDD_GLFN(glCreateShader, GLCREATESHADER)JUDD_GLFN(glGetProgramInfoLog, GLGETPROGRAMINFOLOG)JUDD_GLFN(glDeleteShader, GLDELETESHADER)JUDD_GLFN(glGetShaderInfoLog, GLGETSHADERINFOLOG)JUDD_GLFN(glAttachShader, GLATTACHSHADER)JUDD_GLFN(glDeleteShader, GLDELETESHADER)JUDD_GLFN(glGetProgramiv, GLGETPROGRAMIV)JUDD_GLFN(glLinkProgram, GLLINKPROGRAM)JUDD_GLFN(glBindFragDataLocation, GLBINDFRAGDATALOCATION)JUDD_GLFN(glUseProgram, GLUSEPROGRAM)JUDD_GLFN(glGetAttribLocation, GLGETATTRIBLOCATION)JUDD_GLFN(glGenVertexArrays, GLGENVERTEXARRAYS)JUDD_GLFN(glAttachShader, GLATTACHSHADER)JUDD_GLFN(glDetachShader, GLDETACHSHADER)JUDD_GLFN(glUseProgram, GLUSEPROGRAM)JUDD_GLFN(glGenerateMipmap, GLGENERATEMIPMAP)JUDD_GLFN(glGetUniformLocation, GLGETUNIFORMLOCATION)JUDD_GLFN(glUniform1i, GLUNIFORM1I)JUDD_GLFN(glUniform1f, GLUNIFORM1F)
}
#endif
